### ISSUE TITLE
Docker appliance is decommissioned

### ISSUE THREAD

**Issue by paalbra** [unioslo/zabbix-auto-config#21]
https://hub.docker.com/r/zabbix/zabbix-appliance

> Important information:_ Zabbix Docker Appliance image has been decommissioned and will not be available for 3.0.31, 4.0.19, 4.4.7, 5.0.0 and newer releases. Please use a separate Docker image for each component instead of the all-in-one solution.

The "quick start" in the README needs to be updated.

**Comment by paalbra** [comment]
`podman kube play` would be nice, but it's currently broken in the latest/stable release https://github.com/containers/podman/issues/8608

**Comment by mbakke** [comment]
I'm not sure how useful this is, but here is a Guix OS definition that produces an all-in-one VM with zac, zabbix-cli, and Zabbix 5.2.3.  It assumes that a `zac-config` directory (with `config.ini` etc) exists next to zac.scm:

https://gist.github.com/mbakke/bae11462a5a9c84ea27218f340d14999

(Note: it depends on the [guix-uio](https://github.com/mbakke/guix-uio-free) channel)

It can be used with `guix system vm zac.scm`, which returns a QEMU script for a volatile VM, i.e.:

```
$(guix system vm zac.scm) -m 2g -smp 2 -enable-kvm -vga virtio
```

[GNU Guix](https://guix.gnu.org/) runs on any distro, but may be a little overkill just for testing zabbix-auto-config...

The configuration can be adapted to work with `guix system docker-image` and published as a CI job perhaps?

**Comment by paalbra** [comment]
I'm not familiar with Guix myself. I have this that works with podman (but it got broken i 2.2.x).

I expect that this will work once more in a 2.2.2 or 3.0 release.

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: zabbix
spec:
  containers:
    - image: docker.io/zabbix/zabbix-web-nginx-pgsql:latest
      name: zabbix-web-nginx
      env:
        - name: DB_SERVER_HOST
          value: 127.0.0.1
        - name: PHP_TZ
          value: Europe/Oslo
        - name: POSTGRES_DB
          value: zabbix
        - name: POSTGRES_PASSWORD
          value: secret
        - name: POSTGRES_USER
          value: zabbix
        - name: ZBX_SERVER_HOST
          value: 127.0.0.1
      ports:
        - containerPort: 8080
          hostPort: 8080
          protocol: TCP
    - image: docker.io/library/postgres:latest
      name: postgres
      env:
        - name: POSTGRES_DB
          value: zabbix
        - name: POSTGRES_PASSWORD
          value: secret
        - name: POSTGRES_USER
          value: zabbix
      ports:
        - containerPort: 5432
          hostPort: 5432
          protocol: TCP
    - image: docker.io/zabbix/zabbix-server-pgsql:latest
      name: zabbix-server
      env:
        - name: DB_SERVER_HOST
          value: 127.0.0.1
        - name: POSTGRES_DB
          value: zabbix
        - name: POSTGRES_PASSWORD
          value: secret
        - name: POSTGRES_USER
          value: zabbix
    restartPolicy: Never
```
