### ISSUE TITLE
Should crash if configured collectors are missing

### ISSUE THREAD

**Issue by paalbra** [unioslo/zabbix-auto-config#57]
If you have a configured collector, but the collector is missing, zac will just continue:

https://github.com/unioslo/zabbix-auto-config/blob/2b45f1cb7da0d46b8b218005ebbf751cb17f8793/zabbix_auto_config/__init__.py#L29-L33

This might lead to unexpected behavior and bad results. It's probably better to raise a `ZACException` and crash? Thoughts?

**Comment by pederhan** [comment]
We don't have the manpower to babysit bad source collectors and host modifiers, so failing straight up would not be ideal for us. If we are provided a bad source collector, it shouldn't interfere with the good ones.

We discussed this issue today, and want to implement a system wherein source collectors (and modifiers?) are disabled after failing X times in Y seconds. This allows us to integrate potentially unstable source collectors without jeopardizing the overall stability of ZAC. To support your proposed behavior there could be a configuration option that bypasses this error tolerance strategy (struggling to come up with a good name for this):

```toml
[zac.source_collectors]
exit_on_error = true # immediately exit upon encountering a failing source collector
```

Some source collectors might be more unstable than others; would it make sense for an overall failure tolerance setting, which can be optionally overridden by individual source collectors? Something like this for global configuration:

```toml
[zac.source_collectors]
failure_tolerance = 5
failure_interval = 300
```

And this for individual source collector configuration:

```toml
[source_collectors.mysource]
module_name = "mysource"
update_interval = 60
failure_tolerance = 10
failure_interval = 180
```

Alternatively:

```toml
[source_collectors.mysource]
module_name = "mysource"
update_interval = 60

[source_collectors.mysource.failure]
tolerance = 10
interval = 180
```

These are the names suggested by ChatGPT (I struggled to come up with names myself):

1. Alternative names for X (threshold for number of tolerated failures):
    - failure_tolerance
    - failure_threshold
    - failure_limit
    - failure_count
    - failure_maximum

2. Alternative names for Y (duration in which failures are measured):
    - failure_duration
    - failure_window
    - failure_measurement_period
    - failure_timeframe
    - failure_interval
